# Generated by Django 2.1.3 on 2019-05-05 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bank',
            name='created',
        ),
        migrations.RemoveField(
            model_name='bank',
            name='modified',
        ),
    ]
